name: build ee

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: setup ansible builder
        run: python3 -m pip install ansible-builder
      # - name: build image
      #   run: ansible-builder build -v 3 -t ghcr.io/zaki-lknr/ee-example:latest
      # - run: podman image ls
      - name: create Containerfile
        run: ansible-builder create
      - run: ls . context
      - uses: docker/login-action@v2
        with:
          username: zaki-lknr
          password: ${{ secrets.PERSONAL_TOKEN }}
          registry: ghcr.io
      - name: build & push
        uses: docker/build-push-action@v4
        with:
          context: context
          file: context/Containerfile
          push: true
          tags: ghcr.io/zaki-lknr/ee-example:latest
