name: build ee

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'
    # https://docs.docker.com/build/ci/github-actions/manage-tags-labels/

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: setup ansible builder
        run: python3 -m pip install ansible-builder
      # - name: build image
      #   run: ansible-builder build -v 3 -t ghcr.io/zaki-lknr/ee-example:latest
      # - run: podman image ls
      - name: create Containerfile
        run: ansible-builder create
      - id: meta
        # https://docs.docker.com/build/ci/github-actions/manage-tags-labels/
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: ghcr.io/zaki-lknr/ee-example
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: build & push
        uses: docker/build-push-action@v4
        with:
          context: context
          file: context/Containerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
